(define (cube x) (* x x x))

(define (p x) (- (* 3 x) (* 4 (cube x))))

(define (sine angle)
  (if (not (> (abs angle) 0.1))
      angle
      (p (sine (/ angle 3.0)))))


;; 1. Number of times that procedure `p applied when evaluated `(sine 12.15)?
;;
;; If `n is the number of times that procedure `p applied, `n is the smallest
;; number so that `12.15 / (3^n) <= 0.1
;; => n = 5


;; 2. The order of growth in space and number of steps (as function of a) when
;; `(sine a) is evaluated?
;;
;; If we use substitution model to illustrate the process generated by the
;; `sine procedure, we can easily see that when `a is increased a multiplication
;; of 3, it takes only 1 more step (and 1 more space) to evaluate.
;; Thus, the number of step required for `a grows about as fast as the
;; logarithm of `a to the base 3. The process has `(log a) growth.
